### ISSUE TITLE
Roadmap for 2.2.x

### ISSUE THREAD

**Issue by moritzjacobs** [moritzjacobs/mj-gulp-workflow#7]
- [ ] move from npm to yarn
- [ ] mock rfg API for test – does that make any sense?
- [ ] refactoring
- [ ] some typescript would be awesome...
- [ ] can we remove some configuration nobody ever uses?

@hoffmannclaus I'm gladly taking more PRs for this, should be a good way to get more into js/ts/this shit 💩

**Comment by hoffmannclaus** [comment]
absolutely approve of the following: 

- [ ] (re)move rfg API unit tests - probably to an indipendent test. 
- [ ] remove configuration and create defaults: most of the time there aren't any changes in a lot of the configs and we would get rid of the "you need to update your config or your workflow breaks after there was a change" - problem. 
- [ ] sweet, sweet refactoring.

I don't really have an opinion on typescript and yarn yet, as I haven't spent any time working with it.
